# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(944, 599)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.btn_quit = QtWidgets.QPushButton(self.centralWidget)
        self.btn_quit.setGeometry(QtCore.QRect(843, 514, 94, 32))
        self.btn_quit.setObjectName("btn_quit")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(12, 6, 831, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_20 = QtWidgets.QLabel(self.tab_7)
        self.label_20.setGeometry(QtCore.QRect(20, 12, 775, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("整体视图.jpg"))
        self.label_20.setScaledContents(True)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.btn_login = QtWidgets.QPushButton(self.tab_7)
        self.btn_login.setGeometry(QtCore.QRect(743, 434, 68, 31))
        self.btn_login.setObjectName("btn_login")
        self.lineEdit_login_passwd = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_login_passwd.setGeometry(QtCore.QRect(463, 438, 278, 19))
        self.lineEdit_login_passwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_login_passwd.setObjectName("lineEdit_login_passwd")
        self.label_26 = QtWidgets.QLabel(self.tab_7)
        self.label_26.setGeometry(QtCore.QRect(380, 438, 75, 19))
        self.label_26.setObjectName("label_26")
        self.lineEdit_login_username = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_login_username.setGeometry(QtCore.QRect(92, 438, 278, 19))
        self.lineEdit_login_username.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_login_username.setAutoFillBackground(False)
        self.lineEdit_login_username.setObjectName("lineEdit_login_username")
        self.label_27 = QtWidgets.QLabel(self.tab_7)
        self.label_27.setGeometry(QtCore.QRect(21, 438, 63, 19))
        self.label_27.setObjectName("label_27")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(250, 40, 341, 381))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_CTscan_scan_mode = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox_CTscan_scan_mode.setFont(font)
        self.comboBox_CTscan_scan_mode.setObjectName("comboBox_CTscan_scan_mode")
        self.comboBox_CTscan_scan_mode.addItem("")
        self.comboBox_CTscan_scan_mode.addItem("")
        self.comboBox_CTscan_scan_mode.addItem("")
        self.comboBox_CTscan_scan_mode.addItem("")
        self.comboBox_CTscan_scan_mode.addItem("")
        self.comboBox_CTscan_scan_mode.addItem("")
        self.gridLayout.addWidget(self.comboBox_CTscan_scan_mode, 6, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 4, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setMaximumSize(QtCore.QSize(179, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 6, 0, 1, 1)
        self.lineEdit_CTscan_parameter_L = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_CTscan_parameter_L.setObjectName("lineEdit_CTscan_parameter_L")
        self.gridLayout.addWidget(self.lineEdit_CTscan_parameter_L, 4, 1, 1, 1)
        self.lineEdit_CTscan_parameter_K = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_CTscan_parameter_K.setObjectName("lineEdit_CTscan_parameter_K")
        self.gridLayout.addWidget(self.lineEdit_CTscan_parameter_K, 2, 1, 1, 1)
        self.btn_CTscan_stop_scan = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_CTscan_stop_scan.setFont(font)
        self.btn_CTscan_stop_scan.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btn_CTscan_stop_scan.setObjectName("btn_CTscan_stop_scan")
        self.gridLayout.addWidget(self.btn_CTscan_stop_scan, 7, 1, 1, 1)
        self.btn_CTscan_parameter_write = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_CTscan_parameter_write.setObjectName("btn_CTscan_parameter_write")
        self.gridLayout.addWidget(self.btn_CTscan_parameter_write, 5, 0, 1, 2)
        self.btn_CTscan_start_scan = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_CTscan_start_scan.setFont(font)
        self.btn_CTscan_start_scan.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.btn_CTscan_start_scan.setObjectName("btn_CTscan_start_scan")
        self.gridLayout.addWidget(self.btn_CTscan_start_scan, 7, 0, 1, 1)
        self.lineEdit_CTscan_parameter_N = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_CTscan_parameter_N.setObjectName("lineEdit_CTscan_parameter_N")
        self.gridLayout.addWidget(self.lineEdit_CTscan_parameter_N, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 2, 0, 1, 1)
        self.lineEdit_CTscan_parameter_H = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_CTscan_parameter_H.setObjectName("lineEdit_CTscan_parameter_H")
        self.gridLayout.addWidget(self.lineEdit_CTscan_parameter_H, 3, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 0, 1, 1)
        self.lineEdit_CTscan_parameter_P = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_CTscan_parameter_P.setObjectName("lineEdit_CTscan_parameter_P")
        self.gridLayout.addWidget(self.lineEdit_CTscan_parameter_P, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_5)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 819, 459))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setGeometry(QtCore.QRect(0, 0, 261, 441))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(220, 370, 219, 419))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 231, 402))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self._2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self._2.setContentsMargins(11, 11, 11, 11)
        self._2.setSpacing(6)
        self._2.setObjectName("_2")
        self.comboBox_displacement_move_displacement_number = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_displacement_move_displacement_number.setObjectName("comboBox_displacement_move_displacement_number")
        self.comboBox_displacement_move_displacement_number.addItem("")
        self.comboBox_displacement_move_displacement_number.addItem("")
        self.comboBox_displacement_move_displacement_number.addItem("")
        self.comboBox_displacement_move_displacement_number.addItem("")
        self._2.addWidget(self.comboBox_displacement_move_displacement_number, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self._2.addWidget(self.label_8, 3, 1, 1, 1)
        self.comboBox_displacement_move_displacement_movement_mode = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_displacement_move_displacement_movement_mode.setEnabled(False)
        self.comboBox_displacement_move_displacement_movement_mode.setObjectName("comboBox_displacement_move_displacement_movement_mode")
        self.comboBox_displacement_move_displacement_movement_mode.addItem("")
        self.comboBox_displacement_move_displacement_movement_mode.addItem("")
        self._2.addWidget(self.comboBox_displacement_move_displacement_movement_mode, 8, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self._2.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self._2.addWidget(self.label_4, 0, 1, 1, 1)
        self.comboBox_displacement_move_displacement_velocity = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_displacement_move_displacement_velocity.setEnabled(False)
        self.comboBox_displacement_move_displacement_velocity.setObjectName("comboBox_displacement_move_displacement_velocity")
        self.comboBox_displacement_move_displacement_velocity.addItem("")
        self.comboBox_displacement_move_displacement_velocity.addItem("")
        self.comboBox_displacement_move_displacement_velocity.addItem("")
        self._2.addWidget(self.comboBox_displacement_move_displacement_velocity, 10, 1, 1, 1)
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis.setObjectName("comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis")
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis.addItem("")
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis.addItem("")
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis.addItem("")
        self._2.addWidget(self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self._2.addWidget(self.label_7, 7, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self._2.addWidget(self.label_10, 9, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self._2.addWidget(self.label_9, 5, 1, 1, 1)
        self.comboBox_displacement_move_displacement_type = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_displacement_move_displacement_type.setObjectName("comboBox_displacement_move_displacement_type")
        self.comboBox_displacement_move_displacement_type.addItem("")
        self.comboBox_displacement_move_displacement_type.addItem("")
        self._2.addWidget(self.comboBox_displacement_move_displacement_type, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self._2.addWidget(self.label_11, 11, 1, 1, 1)
        self.comboBox_displacement_move_displacement_units = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_displacement_move_displacement_units.setEnabled(False)
        self.comboBox_displacement_move_displacement_units.setObjectName("comboBox_displacement_move_displacement_units")
        self.comboBox_displacement_move_displacement_units.addItem("")
        self.comboBox_displacement_move_displacement_units.addItem("")
        self.comboBox_displacement_move_displacement_units.addItem("")
        self._2.addWidget(self.comboBox_displacement_move_displacement_units, 12, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_2.setGeometry(QtCore.QRect(260, 0, 551, 211))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 121, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(170, 30, 211, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_displacement_move_input_displacement = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_displacement_move_input_displacement.setObjectName("lineEdit_displacement_move_input_displacement")
        self.verticalLayout_2.addWidget(self.lineEdit_displacement_move_input_displacement)
        self.lineEdit_displacement_move_current_displacement = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_displacement_move_current_displacement.setEnabled(False)
        self.lineEdit_displacement_move_current_displacement.setObjectName("lineEdit_displacement_move_current_displacement")
        self.verticalLayout_2.addWidget(self.lineEdit_displacement_move_current_displacement)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(380, 40, 121, 111))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_displacement_move_unit1 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_displacement_move_unit1.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_displacement_move_unit1.setFont(font)
        self.label_displacement_move_unit1.setObjectName("label_displacement_move_unit1")
        self.verticalLayout_3.addWidget(self.label_displacement_move_unit1)
        self.label_displacement_move_unit2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_displacement_move_unit2.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_displacement_move_unit2.setFont(font)
        self.label_displacement_move_unit2.setObjectName("label_displacement_move_unit2")
        self.verticalLayout_3.addWidget(self.label_displacement_move_unit2)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_3.setGeometry(QtCore.QRect(260, 210, 551, 221))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btn_displacement_move_start_move = QtWidgets.QPushButton(self.frame_3)
        self.btn_displacement_move_start_move.setGeometry(QtCore.QRect(40, 30, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_displacement_move_start_move.setFont(font)
        self.btn_displacement_move_start_move.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.btn_displacement_move_start_move.setObjectName("btn_displacement_move_start_move")
        self.btn_displacement_move_stop_move = QtWidgets.QPushButton(self.frame_3)
        self.btn_displacement_move_stop_move.setGeometry(QtCore.QRect(210, 30, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_displacement_move_stop_move.setFont(font)
        self.btn_displacement_move_stop_move.setStyleSheet("background-color:rgb(255, 0, 0)")
        self.btn_displacement_move_stop_move.setObjectName("btn_displacement_move_stop_move")
        self.btn_displacement_move_save_all = QtWidgets.QPushButton(self.frame_3)
        self.btn_displacement_move_save_all.setEnabled(True)
        self.btn_displacement_move_save_all.setGeometry(QtCore.QRect(390, 30, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_displacement_move_save_all.setFont(font)
        self.btn_displacement_move_save_all.setObjectName("btn_displacement_move_save_all")
        self.btn_displacement_move_initiallize_motor = QtWidgets.QPushButton(self.frame_3)
        self.btn_displacement_move_initiallize_motor.setGeometry(QtCore.QRect(40, 120, 101, 71))
        self.btn_displacement_move_initiallize_motor.setObjectName("btn_displacement_move_initiallize_motor")
        self.btn_displacement_move_kill_all = QtWidgets.QPushButton(self.frame_3)
        self.btn_displacement_move_kill_all.setEnabled(True)
        self.btn_displacement_move_kill_all.setGeometry(QtCore.QRect(210, 120, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_displacement_move_kill_all.setFont(font)
        self.btn_displacement_move_kill_all.setObjectName("btn_displacement_move_kill_all")
        self.btn_displacement_move_upload = QtWidgets.QPushButton(self.frame_3)
        self.btn_displacement_move_upload.setEnabled(True)
        self.btn_displacement_move_upload.setGeometry(QtCore.QRect(390, 120, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_displacement_move_upload.setFont(font)
        self.btn_displacement_move_upload.setObjectName("btn_displacement_move_upload")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.scrollArea_2, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btn_log_write = QtWidgets.QPushButton(self.tab_2)
        self.btn_log_write.setGeometry(QtCore.QRect(410, 410, 396, 36))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_log_write.setFont(font)
        self.btn_log_write.setObjectName("btn_log_write")
        self.textEdit_log_daily_log = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_log_daily_log.setGeometry(QtCore.QRect(7, 37, 397, 409))
        self.textEdit_log_daily_log.setObjectName("textEdit_log_daily_log")
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(410, 3, 396, 28))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(7, 3, 397, 28))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.textEdit_log_manual_record = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_log_manual_record.setGeometry(QtCore.QRect(410, 37, 396, 367))
        self.textEdit_log_manual_record.setObjectName("textEdit_log_manual_record")
        self.btn_log_write.raise_()
        self.label_28.raise_()
        self.label_19.raise_()
        self.textEdit_log_daily_log.raise_()
        self.textEdit_log_manual_record.raise_()
        self.label_19.raise_()
        self.btn_log_write.raise_()
        self.textEdit_log_daily_log.raise_()
        self.label_28.raise_()
        self.label_19.raise_()
        self.textEdit_log_manual_record.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.textBrowser_doc = QtWidgets.QTextBrowser(self.tab_9)
        self.textBrowser_doc.setGeometry(QtCore.QRect(10, 10, 799, 443))
        self.textBrowser_doc.setObjectName("textBrowser_doc")
        self.tabWidget.addTab(self.tab_9, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 944, 26))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CT操作平台"))
        self.btn_quit.setText(_translate("MainWindow", "退出系统"))
        self.btn_login.setText(_translate("MainWindow", "登录"))
        self.label_26.setText(_translate("MainWindow", "          密码："))
        self.label_27.setText(_translate("MainWindow", "用户名：   "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "用户控制"))
        self.comboBox_CTscan_scan_mode.setItemText(0, _translate("MainWindow", "传统相位步进"))
        self.comboBox_CTscan_scan_mode.setItemText(1, _translate("MainWindow", "交叉相位步进"))
        self.comboBox_CTscan_scan_mode.setItemText(2, _translate("MainWindow", "周相位步进"))
        self.comboBox_CTscan_scan_mode.setItemText(3, _translate("MainWindow", "免相位步进"))
        self.comboBox_CTscan_scan_mode.setItemText(4, _translate("MainWindow", "正反投影"))
        self.comboBox_CTscan_scan_mode.setItemText(5, _translate("MainWindow", "备用"))
        self.label_25.setText(_translate("MainWindow", "样品视场Y方向长度 L："))
        self.label_24.setText(_translate("MainWindow", "样品高度 H:"))
        self.label_17.setText(_translate("MainWindow", "扫描方式:"))
        self.lineEdit_CTscan_parameter_L.setText(_translate("MainWindow", "0"))
        self.lineEdit_CTscan_parameter_K.setText(_translate("MainWindow", "0"))
        self.btn_CTscan_stop_scan.setText(_translate("MainWindow", "急停"))
        self.btn_CTscan_parameter_write.setText(_translate("MainWindow", "写入以上参数"))
        self.btn_CTscan_start_scan.setText(_translate("MainWindow", "开始扫描"))
        self.lineEdit_CTscan_parameter_N.setText(_translate("MainWindow", "0"))
        self.label_22.setText(_translate("MainWindow", "G1光栅步进数 N:"))
        self.label_23.setText(_translate("MainWindow", "每圈采集次数 K："))
        self.lineEdit_CTscan_parameter_H.setText(_translate("MainWindow", "0"))
        self.label_21.setText(_translate("MainWindow", "G1光栅周期 P:"))
        self.lineEdit_CTscan_parameter_P.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "扫描控制"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "影像显示"))
        self.label_5.setText(_translate("MainWindow", "请选择参数"))
        self.comboBox_displacement_move_displacement_number.setItemText(0, _translate("MainWindow", "G0光栅"))
        self.comboBox_displacement_move_displacement_number.setItemText(1, _translate("MainWindow", "G1光栅"))
        self.comboBox_displacement_move_displacement_number.setItemText(2, _translate("MainWindow", "样品台"))
        self.comboBox_displacement_move_displacement_number.setItemText(3, _translate("MainWindow", "G2光栅"))
        self.label_8.setText(_translate("MainWindow", "位移台类型"))
        self.comboBox_displacement_move_displacement_movement_mode.setItemText(0, _translate("MainWindow", "相对运动"))
        self.comboBox_displacement_move_displacement_movement_mode.setItemText(1, _translate("MainWindow", "绝对运动"))
        self.label_6.setText(_translate("MainWindow", "位移台序号"))
        self.label_4.setText(_translate("MainWindow", "请选择参数"))
        self.comboBox_displacement_move_displacement_velocity.setItemText(0, _translate("MainWindow", "正常"))
        self.comboBox_displacement_move_displacement_velocity.setItemText(1, _translate("MainWindow", "极慢"))
        self.comboBox_displacement_move_displacement_velocity.setItemText(2, _translate("MainWindow", "快一点"))
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis.setItemText(0, _translate("MainWindow", "Z"))
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis.setItemText(1, _translate("MainWindow", "Y"))
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis.setItemText(2, _translate("MainWindow", "X"))
        self.label_7.setText(_translate("MainWindow", "运动模式"))
        self.label_10.setText(_translate("MainWindow", "运动速度"))
        self.label_9.setText(_translate("MainWindow", "轴名称"))
        self.comboBox_displacement_move_displacement_type.setItemText(0, _translate("MainWindow", "平移"))
        self.comboBox_displacement_move_displacement_type.setItemText(1, _translate("MainWindow", "旋转"))
        self.label_11.setText(_translate("MainWindow", "距离单位"))
        self.comboBox_displacement_move_displacement_units.setItemText(0, _translate("MainWindow", "毫米或度"))
        self.comboBox_displacement_move_displacement_units.setItemText(1, _translate("MainWindow", "微米或分"))
        self.comboBox_displacement_move_displacement_units.setItemText(2, _translate("MainWindow", "脉冲"))
        self.label.setText(_translate("MainWindow", "输入运动位移"))
        self.label_2.setText(_translate("MainWindow", "位移台当前位置"))
        self.lineEdit_displacement_move_input_displacement.setText(_translate("MainWindow", "0"))
        self.lineEdit_displacement_move_current_displacement.setText(_translate("MainWindow", "0.0000"))
        self.label_displacement_move_unit1.setText(_translate("MainWindow", "mm"))
        self.label_displacement_move_unit2.setText(_translate("MainWindow", "mm"))
        self.btn_displacement_move_start_move.setText(_translate("MainWindow", "移动"))
        self.btn_displacement_move_stop_move.setText(_translate("MainWindow", "KILL"))
        self.btn_displacement_move_save_all.setText(_translate("MainWindow", "保存参数"))
        self.btn_displacement_move_initiallize_motor.setText(_translate("MainWindow", "初始化"))
        self.btn_displacement_move_kill_all.setText(_translate("MainWindow", "KILL ALL"))
        self.btn_displacement_move_upload.setText(_translate("MainWindow", "上传参数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "设备检测"))
        self.btn_log_write.setText(_translate("MainWindow", "写入日志"))
        self.label_28.setText(_translate("MainWindow", "手动记录"))
        self.label_19.setText(_translate("MainWindow", "当天操作历史"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "操作日志"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "使用帮助"))

